declare const entityIdBrand: unique symbol;

export type EntityId<TName extends string> = string & {
  readonly [entityIdBrand]: TName;
};

export type UserId = EntityId<'User'>;
export type PropertyId = EntityId<'Property'>;
export type UnitId = EntityId<'Unit'>;
export type SpaceId = EntityId<'Space'>;
export type PartyId = EntityId<'Party'>;
export type ContactPointId = EntityId<'ContactPoint'>;
export type PartyAddressId = EntityId<'PartyAddress'>;
export type OwnershipPeriodId = EntityId<'OwnershipPeriod'>;
export type TenancyId = EntityId<'Tenancy'>;
export type TenancyPartyId = EntityId<'TenancyParty'>;
export type LeaseAgreementId = EntityId<'LeaseAgreement'>;
export type LeaseAgreementPartyId = EntityId<'LeaseAgreementParty'>;
export type LeaseAmendmentId = EntityId<'LeaseAmendment'>;
export type TenancyTermVersionId = EntityId<'TenancyTermVersion'>;
export type DocumentId = EntityId<'Document'>;
export type DocumentVersionId = EntityId<'DocumentVersion'>;
export type DocumentLinkId = EntityId<'DocumentLink'>;
export type InspectionId = EntityId<'Inspection'>;
export type InspectionSchemaVersionId = EntityId<'InspectionSchemaVersion'>;
export type InspectionSchemaSectionId = EntityId<'InspectionSchemaSection'>;
export type InspectionSchemaItemId = EntityId<'InspectionSchemaItem'>;
export type InspectionResponseId = EntityId<'InspectionResponse'>;
export type InspectionFindingId = EntityId<'InspectionFinding'>;
export type InspectionEvidenceId = EntityId<'InspectionEvidence'>;
export type InspectionSignatureId = EntityId<'InspectionSignature'>;
export type InspectionUnlockEventId = EntityId<'InspectionUnlockEvent'>;
export type InspectionFinalizationId = EntityId<'InspectionFinalization'>;

export const asUserId = (value: string): UserId => value as UserId;
export const asPropertyId = (value: string): PropertyId => value as PropertyId;
export const asUnitId = (value: string): UnitId => value as UnitId;
export const asSpaceId = (value: string): SpaceId => value as SpaceId;
export const asPartyId = (value: string): PartyId => value as PartyId;
export const asContactPointId = (value: string): ContactPointId => value as ContactPointId;
export const asPartyAddressId = (value: string): PartyAddressId => value as PartyAddressId;
export const asOwnershipPeriodId = (value: string): OwnershipPeriodId => value as OwnershipPeriodId;
export const asTenancyId = (value: string): TenancyId => value as TenancyId;
export const asTenancyPartyId = (value: string): TenancyPartyId => value as TenancyPartyId;
export const asLeaseAgreementId = (value: string): LeaseAgreementId => value as LeaseAgreementId;
export const asLeaseAgreementPartyId = (value: string): LeaseAgreementPartyId => value as LeaseAgreementPartyId;
export const asLeaseAmendmentId = (value: string): LeaseAmendmentId => value as LeaseAmendmentId;
export const asTenancyTermVersionId = (value: string): TenancyTermVersionId => value as TenancyTermVersionId;
export const asDocumentId = (value: string): DocumentId => value as DocumentId;
export const asDocumentVersionId = (value: string): DocumentVersionId => value as DocumentVersionId;
export const asDocumentLinkId = (value: string): DocumentLinkId => value as DocumentLinkId;
export const asInspectionId = (value: string): InspectionId => value as InspectionId;
export const asInspectionSchemaVersionId = (value: string): InspectionSchemaVersionId => value as InspectionSchemaVersionId;
export const asInspectionSchemaSectionId = (value: string): InspectionSchemaSectionId => value as InspectionSchemaSectionId;
export const asInspectionSchemaItemId = (value: string): InspectionSchemaItemId => value as InspectionSchemaItemId;
export const asInspectionResponseId = (value: string): InspectionResponseId => value as InspectionResponseId;
export const asInspectionFindingId = (value: string): InspectionFindingId => value as InspectionFindingId;
export const asInspectionEvidenceId = (value: string): InspectionEvidenceId => value as InspectionEvidenceId;
export const asInspectionSignatureId = (value: string): InspectionSignatureId => value as InspectionSignatureId;
export const asInspectionUnlockEventId = (value: string): InspectionUnlockEventId => value as InspectionUnlockEventId;
export const asInspectionFinalizationId = (value: string): InspectionFinalizationId => value as InspectionFinalizationId;
